# Generated by Django 5.2.13 on 2026-05-05 12:24

from django.db import migrations, models

import apps.users.models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={"ordering": ("email",)},
        ),
        migrations.AlterModelManagers(
            name="customuser",
            managers=[
                ("objects", apps.users.models.CustomUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="email address"
            ),
        ),
    ]
