# Generated by Django 5.2.13 on 2026-05-04 09:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("roles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="users",
            field=models.ManyToManyField(
                blank=True, related_name="studybuddy_roles", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
