# Generated by Django 5.2.13 on 2026-05-05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roles", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="role",
            old_name="name",
            new_name="display_name",
        ),
        migrations.AlterModelOptions(
            name="role",
            options={"ordering": ("display_name",)},
        ),
        migrations.AlterField(
            model_name="role",
            name="display_name",
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name="role",
            name="slug",
            field=models.SlugField(unique=True),
        ),
        migrations.AddField(
            model_name="role",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="role",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
