# Generated by Django 5.2.13 on 2026-05-18 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insights", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studyinsight",
            name="keywords",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
